version: "3.6"

services:

  nginx:
    image: nginx:1.22
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - api-0
      - api-1
      - api-2
      - api-3

  fluentd:
    image: fluentd:v1.14-1
    volumes:
      - ./conf/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/logs
    ports:
      - "24224:24224"

  api-0:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api:src
    runtime: nvidia
    volumes:
      - ./api/model:/model
    environment:
      - DEVICE_NUM=0
      - MODEL_PATH=${MODEL_PATH}
      - SIM_THRESHOLD=${SIM_THRESHOLD}
    deploy:
      replicas: ${REPLICAS}
    entrypoint:
      - uvicorn
    command:
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  api-1:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api:src
    runtime: nvidia
    volumes:
      - ./api/model:/model
    environment:
      - DEVICE_NUM=1
      - MODEL_PATH=${MODEL_PATH}
      - SIM_THRESHOLD=${SIM_THRESHOLD}
    deploy:
      replicas: ${REPLICAS}
    entrypoint:
      - uvicorn
    command:
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  api-2:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api
    runtime: nvidia
    volumes:
      - ./api/model:/model
    environment:
      - DEVICE_NUM=2
      - MODEL_PATH=${MODEL_PATH}
      - SIM_THRESHOLD=${SIM_THRESHOLD}
    deploy:
      replicas: ${REPLICAS}
    entrypoint:
      - uvicorn
    command:
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd
        tag: "{{.Name}}"
    depends_on:
      - fluentd

  api-3:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api
    runtime: nvidia
    volumes:
      - ./api/model:/model
    environment:
      - DEVICE_NUM=3
      - MODEL_PATH=${MODEL_PATH}
      - SIM_THRESHOLD=${SIM_THRESHOLD}
    deploy:
      replicas: ${REPLICAS}
    entrypoint:
      - uvicorn
    command:
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd
        tag: "{{.Name}}"
    depends_on:
      - fluentd
    # network_mode: host

  # faiss:
  #   build:
  #     context: ./faiss
  #     dockerfile: Dockerfile
  #   image: faiss:cpu
  #   runtime: nvidia
  #   volumes:
  #     - ./faiss/title_embeddings:/title_embeddings
  #   entrypoint:
  #     - uvicorn
  #   command:
  #     - "main:app"
  #     - "--host"
  #     - "0.0.0.0"
  #     - "--port"
  #     - "7000"
